on:
  push:
  pull_request:
    tags:
      - '*'
      
permissions:
  contents: write
name: Build
jobs:
  build:
    strategy:
      fail-fast: true
      matrix: 
        targets: [esp32s3]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-tags: true
    - name: Rename artifact
      run: |
        git describe
